name = "pennydrop"
main = "src/worker.js"
compatibility_date = "2026-03-19"

# This links your code to the Database where puzzles are stored
[[kv_namespaces]]
binding = "PUZZLE_STORE"
id = "725656297823478480d12f46d6d7f875"

# This links to your High Score database
[[d1_databases]]
binding = "DB"
database_name = "penny_drop_scores"
database_id = "f6e33361-2622-477c-895f-050b9d622bb3"
